export const SAVE_DATA_LOCATION_DATA = 'SAVE_DATA_LOCATION_DATA';
export const SAVE_CONTACT_LOCATION_DATA = 'SAVE_CONTACT_LOCATION_DATA';
export const LOAD_ASYNC_STORAGE_DATA = 'LOAD_ASYNC_STORAGE_DATA';
